services:
  windows:
    image: dockurr/windows
    environment:
      DISK_SIZE: "25G"
      RAM_SIZE: "2G"
      CPU_CORES: "2"
      DISK_TYPE: "ide"
      VERSION: "win8"
    devices:
      - /dev/kvm
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    volumes:
      - /root/ActionDocker:/storage
    stop_grace_period: 2m
